### ISSUE TITLE
App crash while mounted on MK1

### ISSUE THREAD

**Issue by frizensami** [yonahbox/yonahtelemetry#29]
07-12 17:21:14.708 31366-31366/? E/AndroidRuntime: FATAL EXCEPTION: main
07-12 17:21:14.708 31366-31366/? E/AndroidRuntime: Process: sg.yonah.yonahtelemetry, PID: 31366
07-12 17:21:14.708 31366-31366/? E/AndroidRuntime: java.lang.RuntimeException: WakeLock under-locked sg.yonah.yonahtelemetry.MainService
07-12 17:21:14.708 31366-31366/? E/AndroidRuntime:     at android.os.PowerManager$WakeLock.release(PowerManager.java:1296)
07-12 17:21:14.708 31366-31366/? E/AndroidRuntime:     at android.os.PowerManager$WakeLock.release(PowerManager.java:1267)
07-12 17:21:14.708 31366-31366/? E/AndroidRuntime:     at sg.yonah.yonahtelemetry.MainService$2.onReceive(MainService.java:226)
07-12 17:21:14.708 31366-31366/? E/AndroidRuntime:     at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
07-12 17:21:14.708 31366-31366/? E/AndroidRuntime:     at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
07-12 17:21:14.708 31366-31366/? E/AndroidRuntime:     at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116)
07-12 17:21:14.708 31366-31366/? E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:111)
07-12 17:21:14.708 31366-31366/? E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:207)
07-12 17:21:14.708 31366-31366/? E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5765)
07-12 17:21:14.708 31366-31366/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
07-12 17:21:14.708 31366-31366/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
07-12 17:21:14.708 31366-31366/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:683)

Connected to Pixhawk, left there for about 5 minutes, screen was off after a while. Performed successful arm and disarm remotely through encryption proxy. When USB was plugged out - app screen stopped updating. Next connection of USB caused crash.

**Comment by frizensami** [comment]
Resolved by error checking and checking isHeld before wakelock is released and acquired.
